# Carregando bibliotecas

In [1]:
import numpy as np
import pandas as pd

# Criando um NDarray

In [2]:
nd1 = np.array([1, 2.5, 7, -78, -0.9, 130, 25])
nd1

array([  1. ,   2.5,   7. , -78. ,  -0.9, 130. ,  25. ])

# Criando um NDArray com os valores de 0 a 10.

In [7]:
nd2 = np.arange(11)
nd2
type(nd2)

numpy.ndarray

# Criando um NDArray de dimensão 2x5 com valores 1.

In [11]:
nd3 = np.ones((2, 5))
nd3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Criando um NDArray com valores de 1 a 100, com intervalos de 3 em 3 e mostrando sua raiz quadrada

In [36]:
nd4 = np.arange(1,101,3)
nd4Sqrt = np.sqrt(nd4)
nd4Sqrt

array([ 1.        ,  2.        ,  2.64575131,  3.16227766,  3.60555128,
        4.        ,  4.35889894,  4.69041576,  5.        ,  5.29150262,
        5.56776436,  5.83095189,  6.08276253,  6.32455532,  6.55743852,
        6.78232998,  7.        ,  7.21110255,  7.41619849,  7.61577311,
        7.81024968,  8.        ,  8.18535277,  8.36660027,  8.54400375,
        8.71779789,  8.88819442,  9.05538514,  9.21954446,  9.38083152,
        9.53939201,  9.69535971,  9.8488578 , 10.        ])

# Alterando a décima posição do NDArray criado no exercício 5 com o dobro do seu valor.


In [37]:
nd4

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [38]:
nd4[9] *=2
nd4

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  56,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

# Criando um dataframe (pandas)

In [39]:
estados_cidades = {
    'São Paulo': ['São Paulo', 'Campinas', 'Guarulhos'],
    'Rio de Janeiro': ['Rio de Janeiro', 'Niterói', 'Campos dos Goytacazes'],
    'Minas Gerais': ['Belo Horizonte', 'Uberlândia', 'Contagem'],
    'Bahia': ['Salvador', 'Feira de Santana', 'Vitória da Conquista'],
    'Rio Grande do Sul': ['Porto Alegre', 'Caxias do Sul', 'Pelotas'],
    'Paraná': ['Curitiba', 'Londrina', 'Maringá'],
    'Santa Catarina': ['Florianópolis', 'Joinville', 'Blumenau'],
    'Goiás': ['Goiânia', 'Anápolis', 'Aparecida de Goiânia'],
    'Ceará': ['Fortaleza', 'Caucaia', 'Juazeiro do Norte'],
    'Pernambuco': ['Recife', 'Jaboatão dos Guararapes', 'Caruaru']
}
df1 = pd.DataFrame(estados_cidades)
df1

São Paulo         Rio de Janeiro    Minas Gerais                 Bahia  \
0  São Paulo         Rio de Janeiro  Belo Horizonte              Salvador   
1   Campinas                Niterói      Uberlândia      Feira de Santana   
2  Guarulhos  Campos dos Goytacazes        Contagem  Vitória da Conquista   

  Rio Grande do Sul    Paraná Santa Catarina                 Goiás  \
0      Porto Alegre  Curitiba  Florianópolis               Goiânia   
1     Caxias do Sul  Londrina      Joinville              Anápolis   
2           Pelotas   Maringá       Blumenau  Aparecida de Goiânia   

               Ceará               Pernambuco  
0          Fortaleza                   Recife  
1            Caucaia  Jaboatão dos Guararapes  
2  Juazeiro do Norte                  Caruaru

In [41]:
df1.head()

São Paulo         Rio de Janeiro    Minas Gerais                 Bahia  \
0  São Paulo         Rio de Janeiro  Belo Horizonte              Salvador   
1   Campinas                Niterói      Uberlândia      Feira de Santana   
2  Guarulhos  Campos dos Goytacazes        Contagem  Vitória da Conquista   

  Rio Grande do Sul    Paraná Santa Catarina                 Goiás  \
0      Porto Alegre  Curitiba  Florianópolis               Goiânia   
1     Caxias do Sul  Londrina      Joinville              Anápolis   
2           Pelotas   Maringá       Blumenau  Aparecida de Goiânia   

               Ceará               Pernambuco  
0          Fortaleza                   Recife  
1            Caucaia  Jaboatão dos Guararapes  
2  Juazeiro do Norte                  Caruaru

In [42]:
df1.tail()

São Paulo         Rio de Janeiro    Minas Gerais                 Bahia  \
0  São Paulo         Rio de Janeiro  Belo Horizonte              Salvador   
1   Campinas                Niterói      Uberlândia      Feira de Santana   
2  Guarulhos  Campos dos Goytacazes        Contagem  Vitória da Conquista   

  Rio Grande do Sul    Paraná Santa Catarina                 Goiás  \
0      Porto Alegre  Curitiba  Florianópolis               Goiânia   
1     Caxias do Sul  Londrina      Joinville              Anápolis   
2           Pelotas   Maringá       Blumenau  Aparecida de Goiânia   

               Ceará               Pernambuco  
0          Fortaleza                   Recife  
1            Caucaia  Jaboatão dos Guararapes  
2  Juazeiro do Norte                  Caruaru

In [43]:
df1.tail(1)

São Paulo         Rio de Janeiro Minas Gerais                 Bahia  \
2  Guarulhos  Campos dos Goytacazes     Contagem  Vitória da Conquista   

  Rio Grande do Sul   Paraná Santa Catarina                 Goiás  \
2           Pelotas  Maringá       Blumenau  Aparecida de Goiânia   

               Ceará Pernambuco  
2  Juazeiro do Norte    Caruaru

# Subindo um arquivo csv de empresas e tirando a media da quantidade de funcionarios de cada uma e somando todos

In [52]:
dfInc = pd.read_csv("/content/INC 5000 Companies 2019.csv")
dfInc.head()


rank                                   profile               name  \
0     1      https://www.inc.com/profile/freestar           Freestar   
1     2   https://www.inc.com/profile/freightwise        FreightWise   
2     3  https://www.inc.com/profile/ceces-veggie  Cece's Veggie Co.   
3     4      https://www.inc.com/profile/ladyboss           LadyBoss   
4     5        https://www.inc.com/profile/perpay             Perpay   

                         url state       revenue    growth_%  \
0        http://freestar.com    AZ  36.9 Million  36680.3882   
1  http://freightwisellc.com    TN  33.6 Million  30547.9317   
2   http://cecesveggieco.com    TX  24.9 Million  23880.4852   
3        http://ladyboss.com    NM  32.4 Million  21849.8925   
4          http://perpay.com    PA  22.5 Million  18166.4070   

                       industry  workers  previous_workers  founded  \
0       Advertising & Marketing     40.0                 5     2015   
1    Logistics & Transportation     39.0                 8     2015   
2               Food & Beverage    190.0                10     2015   
3  Consumer Products & Services     57.0                 2     2014   
4                        Retail     25.0                 6     2014   

   yrs_on_list         metro          city  
0            1       Phoenix       Phoenix  
1            1     Nashville     Brentwood  
2            1        Austin        Austin  
3            1           NaN   Albuquerque  
4            1  Philadelphia  Philadelphia

## Deixando apenas a coluna name e workers

In [54]:
dfInc = dfInc[["name", "workers"]]
dfInc

name  workers
0                   Freestar     40.0
1                FreightWise     39.0
2          Cece's Veggie Co.    190.0
3                   LadyBoss     57.0
4                     Perpay     25.0
...                      ...      ...
5007  Village Plumbing & Air     88.0
5008  Real Restoration Group    380.0
5009           Naval Systems    187.0
5010             HNM Systems    132.0
5011                 Vivayic     27.0

[5012 rows x 2 columns]

In [56]:
media_funcionarios = dfInc['workers'].mean()
media_funcionarios

242.7830772300938

In [57]:
dfInc['workers'].sum()

1216586.0