#Demonstração NumPY
###Disciplina - Introdução a Ciência de Dados - Univesp
###Videoaula 5
###Prof. Dr. José Eduardo Santarem Segundo

#Importar Biblioteca

In [2]:
import numpy as np

#Gerar Dados Aleatórios

##Gerar um NDArray de 2x3 (duas lista com 3 elementos)

In [3]:
dados=np.random.rand(2,3)

In [4]:
dados

array([[0.12889594, 0.45973808, 0.83388521],
       [0.5362911 , 0.43106149, 0.29274563]])

#Tipo do Array

In [5]:
dados.dtype

dtype('float64')

#Tamanho e quantidade de dimensões

In [6]:
dados.shape

(2, 3)

In [7]:
dados.ndim

2

#Criar ndarray usando a função array
##Ao criar o array a função array tenta utilizar o melhor tipo de dado

In [8]:
lista=[1,2,5,7.8,1.25]

In [9]:
dados2=np.array(lista)

In [10]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [11]:
lista2=[[1,2,3,4],[4,3,2,1]]

In [12]:
dados3=np.array(lista2)

In [13]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

#Outras maneiras de criar arrays

In [14]:
dadoszero=np.zeros(10)

In [15]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
dadoszero2=np.zeros((2,3))

In [17]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
dadosum=np.ones(5)

In [19]:
dadosum

array([1., 1., 1., 1., 1.])

In [20]:
dadosseq=np.arange(10)

In [21]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
dadosseq2=np.arange(0,20,2)

In [23]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
dadosseq.dtype

dtype('int64')

In [25]:
dadosseqf=dadosseq.astype(np.float64)

In [26]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [27]:
dadosseqf.dtype

dtype('float64')

#Aritmética com Arrays

In [28]:
dados4=np.array([[1,2,3],[4,5,6]])

In [29]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [31]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [33]:
dados5=dados4+dados4

In [34]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [35]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

#Indexação

In [37]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
dadosseq[5]

5

## Diferente de uma lista python, um recorte (fatia) de um ndarray sofrerá broadcast - é como se fosse uma view de bando de dados.
##Com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [39]:
dadosseq[3:6]

array([3, 4, 5])

In [40]:
dadosseq[3:6]=20

In [41]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [42]:
fatiadados=dadosseq[2:4]

In [43]:
fatiadados

array([ 2, 20])

In [44]:
fatiadados[1]=2000

In [45]:
fatiadados

array([   2, 2000])

In [46]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [47]:
fatiadados[:]=333

In [48]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#Copiar dados

In [49]:
fatia2=dadosseq[2:4].copy()

In [50]:
fatia2

array([333, 333])

In [51]:
fatia2[:]=111

In [52]:
fatia2

array([111, 111])

In [53]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#Array com mais de uma dimensão

In [54]:
dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [55]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
dados6[1,2]

6

#Máscaras

In [57]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [58]:
mascara=(dadosseq<100)

In [59]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [60]:
dadosseq[dadosseq<20]=8888

In [61]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

#Transposição

In [62]:
dados7=np.arange(15).reshape((3,5))

In [63]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#Multiplicação de Matrizes com Dots

In [65]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

# Vejam que há muitas outras funções que podem ser exploradas como: sin, cos, power, mod, sqrt entre outros